### ISSUE TITLE
Add 'Annode Shape' field to table

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing#141]
Method > Backpack, Canoe/Barge, Raft/Boat 

Add 'Annode Shape' field to the 'Anode Diameter ' and 'Stock Diameter' table, which are present in the Backpack, Canoe/Barge, Raft/Boat sub tabs.

**Comment by steveoh** [comment]
@ToddVolkening I am confused what to do here since Anode Shape is already visible for backpack and canoe/barge.

### Backpack
![image](https://user-images.githubusercontent.com/325813/40998230-58b80fa0-68c4-11e8-8058-8c87203c5f67.png)

### Canoe/Barge
![image](https://user-images.githubusercontent.com/325813/40998246-669ea548-68c4-11e8-979b-985aec69722f.png)

Do you want to move the current anode shape into the place you describe or do you want anode shape to be in both places?

**Comment by steveoh** [comment]
@ToddVolkening any updates on this?

**Comment by ToddVolkening** [comment]
Sorry for the delay, I was out of the office...

I have attached an image which will hopefully provide clarification.

Please relocate the 'Anode Shape' field to the table area that contains the 'Anode Diameter' and 'Stock Diameter' fields.  Similar to the 'Anode Diameter' and 'Stock Diameter' field, the 'Anode Shape' field will be adjusted based on the value entered into the '# Anodes' field.

This request would apply to all equipment types - Backpack, Canoe/Barge, and Raft/Boat.


![efdbase_github 141](https://user-images.githubusercontent.com/35234370/41360429-ff5fa9b4-6ee9-11e8-8a8b-6d8d0e2fa869.PNG)
