### ISSUE TITLE
Inappropriate fields tied to Backpack

### ISSUE THREAD

**Issue by ToddVolkening** [agrc/electrofishing#142]
Method tab > 

'Array Type' and 'Cathode Type' should not appear when a user selects Backpack as an equipment type.

**Comment by steveoh** [comment]
Backpack does not display `array type` or `cathode type`. @ToddVolkening if you were able to make those fields display, please describe how you were able to do that. Otherwise this issue is invalid.

### Backpack
![image](https://user-images.githubusercontent.com/325813/40998230-58b80fa0-68c4-11e8-8058-8c87203c5f67.png)

### Canoe/Barge
![image](https://user-images.githubusercontent.com/325813/40998246-669ea548-68c4-11e8-979b-985aec69722f.png)

### Raft/Boat
![image](https://user-images.githubusercontent.com/325813/40998253-701599ce-68c4-11e8-9fb0-7b74a0959d54.png)

**Comment by steveoh** [comment]
@ToddVolkening any updates on this?
