### ISSUE TITLE
Possible broken relationships

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#280]
Query for sampling events with station ids that are not existing. These are the issues.

**Comment by ToddVolkening** [comment]
I responded to Nathan Kota's recent email and I passed along this question
of how to handle #280 to Craig Walker. I proposed that the regions should
re-enter the stations and have Scott fix the relationship on the back end.
Awaiting response.

[image: Photo]

Todd Volkening
Senior GIS Analyst
M: (801) 244-5878
E: ***@***.*** ***@***.***>

Utah Department of Natural Resources
Division of Wildlife Resources
[image: Facebook icon] <http://facebook.com/UtahDWR>[image: Twitter icon]
<https://twitter.com/UtahDWR>[image: Youtube icon]
<https://www.youtube.com/user/UDWR>[image: Instagram icon]
<https://www.instagram.com/utahdwr/>
wildlife.utah.gov

The content of this email is confidential and intended for the recipient
specified in the message only. It is strictly forbidden to share any part
of this message with any third party without the written consent of the
sender. If you received this message by mistake, please reply to this
message and follow with its deletion so that we can ensure such a mistake
does not occur in the future.

**Comment by ToddVolkening** [comment]
Here is the response and plan proposed by Craig Walker:

Nathan and Scott,

Todd and I have looked over the 9 events that did not have station data
associated with them and our game plan is as follows:

1) create screen shots of the 9 event locations on maps (completed);
2) disseminate these maps to regional personnel responsible for creating
the 9 events;
3) request that the regional personnel provide a "pin" on the map depicting
the location of the associated stations for each of the 9 sampling events;
4) request that regional personnel provide the station name for the
associated stations described in 3 above;
5) use regional station name and location pins to create new stations using
the entry application;
6) provide Scott with a table showing the 9 events (event ID) and the
associated station name and UTM coordinates for stations created in 5
above; and
7) rely on Scott to develop the "behind the scenes" relationship between
the new stations and the associated events described in 6 above.

Please let me know if that is an acceptable course of action.  One
question... Am I okay to let our folks restart data entry (i.e., is the
station creation bug from #280 fixed)?

-CW

[image: Photo]

Todd Volkening
Senior GIS Analyst
M: (801) 244-5878
E: ***@***.*** ***@***.***>

Utah Department of Natural Resources
Division of Wildlife Resources
[image: Facebook icon] <http://facebook.com/UtahDWR>[image: Twitter icon]
<https://twitter.com/UtahDWR>[image: Youtube icon]
<https://www.youtube.com/user/UDWR>[image: Instagram icon]
<https://www.instagram.com/utahdwr/>
wildlife.utah.gov

The content of this email is confidential and intended for the recipient
specified in the message only. It is strictly forbidden to share any part
of this message with any third party without the written consent of the
sender. If you received this message by mistake, please reply to this
message and follow with its deletion so that we can ensure such a mistake
does not occur in the future.

**Comment by stdavis** [comment]
I replied back to Craig's email earlier this morning. 👍

**Comment by nathankota** [comment]
- Four of the affected events were test data.
- Craig will use the app to create new stations for each of the valid events.
- Then request for us to enter the proper station ID for each event

**Comment by nathankota** [comment]
> Of the 9 events originally identified as lacking a relationship with a station, 4 were found to be test events and have been deleted from the geodatabase.  However, 5 events (3 on Center Creek and 2 on Blubber Creek) were still lacking relationships with stations.  For the Center Creek events, the relationships were not established with a preexisting station.  For the Blubber Creek events, the relationships were not established for a new station.  I have gone into the data entry tool and created new stations for the 2 Blubber Creek events.  Please note that I do not know the new station IDs created for the Blubber Creek locations.  Additionally, I have identified the preexisting stations that need to be related to each of the 3 Center Creek events.
> 
> The relationships that need to be established are as follows:

### Blubber Creek

-Event ID 579F55C2-C1E0-4A4D-874C-88027ED80A50 needs to be related to a new station named Blubber Creek Station 1; and

-Event ID 4DDF298F-9BCC-48C1-879F-98C3D2C141FD needs to be related to new station named Blubber Creek Station 2.

### Center Creek

-Event ID 9E589E93-3A08-4A25-8C96-8451D94A42DF needs to be associated with existing station ID 45A544F3-0C2D-46AC-86F0-FA9E99526127;

-Event ID 82555A5E-1C29-47F6-8F24-184202033B42 needs to be associated with existing station ID 78CA4A4B-5782-435B-8435-4DF63AE3A772; and

-Event ID 613D9926-7E22-4F79-818C-6A9D5ED2E2E2 needs to be associated with existing station ID 10032FD0-292D-444D-84D7-C05B93F30D5C.

@stdavis let me know if I can help with this in any way

**Comment by stdavis** [comment]
Thanks for updating the issue! I've got the last one fixed now.

**Comment by nathankota** [comment]
waiting for client validation

**Comment by nathankota** [comment]
validated
