### ISSUE TITLE
Add "Hard Body Part Collection" to Fish Dialog

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#44]
>Add a new tab/sub-tab for ‘Hard body part collection’ as a drop down that's tied to individual fish like Diet, Tag, Health tabs are. Drop down to include: Scale, Spine, Ray, Cleithrum, Otolith, Other

Ref 2) in: https://docs.google.com/document/d/1pTsCfe0-Kmp20vSLy9DJtVIEFB_PwfoabOojmtVQXYM/edit

**Comment by steveoh** [comment]
@ToddVolkening is this what you had in mind? 

![image](https://user-images.githubusercontent.com/325813/37437552-68c702d6-27b3-11e8-9e85-ffd4552b2559.png)
![image](https://user-images.githubusercontent.com/325813/37437527-4da39294-27b3-11e8-85ae-bdcb030ab90b.png)

Is the hard body part collection value related to each tag or the fish?

**Comment by ToddVolkening** [comment]
Hard body parts are tied to an individual fish.  Thanks.  Craig and Todd

Sent from my iPhone

On Mar 14, 2018, at 6:13 PM, steveoh <notifications@github.com> wrote:

@ToddVolkening <https://github.com/toddvolkening> is this what you had in
mind?

[image: image]
<https://user-images.githubusercontent.com/325813/37437552-68c702d6-27b3-11e8-9e85-ffd4552b2559.png>
[image: image]
<https://user-images.githubusercontent.com/325813/37437527-4da39294-27b3-11e8-85ae-bdcb030ab90b.png>

Is the hard body part collection value related to each tag or the fish?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/agrc/electrofishing/issues/44#issuecomment-373217313>,
or mute the thread

**Comment by steveoh** [comment]
@ToddVolkening and Craig, do you have an opinion on the design from the photos? Is that how you think it should look/work?

**Comment by ToddVolkening** [comment]
The Hard Body Parts tab should be analogous to the other sub tabs (e.g
Diet).  It should include:  Was a hard body part collected?  Yes or No.  It
should also include a pick list of body part type, which we will provided.
Thanks.  Craig and Todd

Sent from my iPhone

On Mar 15, 2018, at 12:38 PM, steveoh <notifications@github.com> wrote:

@ToddVolkening <https://github.com/toddvolkening> and Craig, do you have an
opinion on the design from the photos? Is that how you think it should
look/work?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/agrc/electrofishing/issues/44#issuecomment-373480966>,
or mute the thread
