### ISSUE TITLE
Diet Tab unit tweaks

### ISSUE THREAD

**Issue by stdavis** [agrc/electrofishing#52]
- [x] Type: Add units of measurement to the label for Volume and Weight (e.g. Volume (ml) and Weight (g))
- [x] Measurement: Whole numbers not text field with “Null” for presence populated when left blank.  INTEGERS ONLY NO TEXT

Ref 11) & 11a) from https://docs.google.com/document/d/1pTsCfe0-Kmp20vSLy9DJtVIEFB_PwfoabOojmtVQXYM/edit

**Comment by steveoh** [comment]
@ToddVolkening is 32,767 a large enough hole number or do you want to go for 2,147,483,647?

**Comment by ToddVolkening** [comment]
Small integer values for diet tab, with no negative values allowed.  Thanks.

Sent from my iPhone

On Mar 13, 2018, at 7:16 PM, steveoh <notifications@github.com> wrote:

@ToddVolkening <https://github.com/toddvolkening> is 32,767 a large enough
hole number or do you want to go for 2,147,483,647?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/agrc/electrofishing/issues/52#issuecomment-372872190>,
or mute the thread
